### ISSUE TITLE
DOMError at MutationObserver.observe on some Apple devices

### ISSUE THREAD

**Issue by danielr18** [benwiley4000/cassette#325]
Browsers tested:
- Safari 9.1.1 MacOS El Capitan
- Chrome iOS 62.0.3202.70

![image](https://user-images.githubusercontent.com/9046616/50047158-c7dcc080-008e-11e9-953c-2a8f1fdd7b4c.png)

**Comment by benwiley4000** [comment]
@danielr18 maybe you did this already, but could you double-confirm that v2.0.0-alpha.12 fixes this? :)

**Comment by danielr18** [comment]
It's working with v2.0.0-alpha.12

**Comment by benwiley4000** [comment]
Awesome
