### ISSUE TITLE
mediaElementRef Help

### ISSUE THREAD

**Issue by steveambielli** [benwiley4000/cassette#346]
In version 1 I was using onMediaEvent for when the player was paused, etc. What would the correct syntax be for mediaElementRef? In the component I have `mediaElementRef={elem => this.audioElement = elem }`. Thanks!

**Comment by benwiley4000** [comment]
Hey Steve, if you want the quickest fix you can do this:

```jsx
<MediaPlayer
  playlist={myPlaylist}
  mediaElementRef={elem => {
    elem.addEventListener('play', () => console.log('PLAY'));
    elem.addEventListener('pause', () => console.log('PAUSED'));
  }}
/>
```

However in version 2 the recommended way is to surround the entire section of your app that needs access to this state with a `PlayerContextProvider`. So it could look like this:

```jsx
import { PlayerContextProvider, PlayerContextConsumer } from '@cassette/core';
import { MediaPlayerControls } from '@cassette/player'; 

function MyApp() {
  return (
    <PlayerContextProvider playlist={myPlaylist}>
      <div>
        <PlayerContextConsumer>
         {playerContext => <PausedCheck isPaused={playerContext.paused} />}
        </PlayerContextConsumer>
      </div>
     <MediaPlayerControls />
    </PlayerContextProvider>
  );
}

function PausedCheck({ isPaused }) {
  return isPaused ? 'Media is paused' : 'Media is playing';
}
```

There's also the `playerContextFilter` higher-order-component that lets you do this:

```jsx
import { PlayerContextProvider, playerContextFilter } from '@cassette/core';
import { MediaPlayerControls } from '@cassette/player';

function MyApp() {
  return (
    <PlayerContextProvider playlist={myPlaylist}>
      <div>
        <PausedCheck />
      </div>
     <MediaPlayerControls />
    </PlayerContextProvider>
  );
}

function PausedCheck({ paused }) {
  return paused ? 'Media is paused' : 'Media is playing';
}
PausedCheck = playerContextFilter(PausedCheck, ['paused']);
```

**Comment by benwiley4000** [comment]
Not sure if you've found the docs website for Cassette v2, but it's here: https://benwiley4000.github.io/cassette/styleguide

Please let me know if you run into any other questions or other issues! The docs are still in progress and need some work. I'd appreciate any help making them better.

**Comment by benwiley4000** [comment]
Hey @steveambielli - could you let me know if you solved your problem?

**Comment by benwiley4000** [comment]
Closing for now - let me know if you have other questions. :slightly_smiling_face:
