### ISSUE TITLE
@cassette/hooks 2.0.0-alpha.28 in npm doesn't seem to be correct 

### ISSUE THREAD

**Issue by danielr18** [benwiley4000/cassette#388]
![image](https://user-images.githubusercontent.com/9046616/53060195-59eeb400-3498-11e9-958b-dc907a789859.png)

The expected main file is: "dist/es5/cassette-hooks.js"` in the package.json.

**Comment by benwiley4000** [comment]
Ugh sorry, I forgot to change the name in the webpack config. https://github.com/benwiley4000/cassette/blob/next/packages/hooks/webpack.config.js

**Comment by benwiley4000** [comment]
I'll fix it and make a new release

**Comment by benwiley4000** [comment]
It's fixed in [v2.0.0-alpha.29](https://github.com/benwiley4000/cassette/releases/tag/v2.0.0-alpha.29)
