### ISSUE TITLE
Cut beta.0 release (no more breaking changes)

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/cassette#409]
Note to alpha users that now that we've reached a pretty stable API, I plan to cut the first version of the beta release of Cassette v2 in the next 24 hours, unless there are any major objections or concerns about the current version of the API. I want to avoid any breaking changes during the beta phase.

Any features that haven't made it into the [**`next`**](https://github.com/benwiley4000/cassette) branch already will be added in future minor releases (the next one will be v2.1.0). The important thing now is to make sure that any **breaking changes** that need to be made during the alpha stage, have been made. Future breaking changes will need to wait until the v3.0 release, should that ever be needed.

At present the plan is for v2.0.0-beta.0 to be identical (aside from some incoming docs updates) to v2.0.0-alpha.33.

### *Full disclosure..*
.. that the beta deadline has been timed to line up with a talk I'll be giving tomorrow on Cassette at the ForwardJS Conference in Ottawa, Canada. But if there are any serious concerns, I'm fine just cutting a release candidate and delaying the beta.0 release.

There should be a video recording of the talk so I'll try to share it in the docs when it's online.

cc
@Hypnosphi
@erikras
@danielr18
@RobinGiel
@steveambielli
@GrandathePanda 
@csantiago132
@romanlex
@joelrojo
@prettymuchbryce 
@pablopaul
@ays14
@RageMaster14

**Comment by benwiley4000** [comment]
p.s. if anyone feels especially compelled to help me with a last-minute propTypes documentation blitz, it would be much appreciated! 😄 But no worries if you don't have any time.

If you do want to help, you can comment in [this thread](https://github.com/benwiley4000/cassette/issues/405#issuecomment-481366269
) with the list of components you plan to tackle (don't feel pressured to bite off too much... documenting just one component's props is a huge help!)

**Comment by prettymuchbryce** [comment]
This is great Ben. Look forward to digging in more and checking out the talk when it's available. 👏

**Comment by benwiley4000** [comment]
Cassette was release in beta yesterday (v2.0.0-beta.0)!

I'll be posting a changelog for 2.0 soon.

I also gave a presentation on Cassette yesterday which went pretty well I think! The slides are [here](https://docs.google.com/presentation/d/1CcDo1WcF4j6lSnapgBT_mKYgmahQOufbxvvnZTitWZc/edit?usp=sharing) and I'll share the video when it's online.

**Comment by benwiley4000** [comment]
Hey everyone, the [changelog is here](https://github.com/benwiley4000/cassette/blob/next/CHANGELOG.md) and the [docs are here](https://benwiley4000.github.io/cassette/styleguide/).

**Comment by benwiley4000** [comment]
BTW the talk is now online! @prettymuchbryce https://www.youtube.com/watch?v=fsySVdhEErI
