### ISSUE TITLE
ContextProvider/Consumer not working as expected

### ISSUE THREAD

**Issue by rexmortus** [benwiley4000/cassette#413]
Hi @benwiley4000,

Thanks so much for your awesome work!

I've had to rig up my own context provider that wraps the component because, well, I just can't get the one included in your component to work!

Can you please help me understand? Should it not be simply a matter of:

```
import { PlayerContextProvider } from '@cassette/core';
import { MediaPlayer } from '@cassette/player';
...
<PlayerContextProvider>
  <MediaPlayer/>
</PlayerContextProvider>
```

And then, elsewhere:

```
import { PlayerContextConsumer } from '@cassette/core';
...
<PlayerContextConsumer filterList={['currentTime', 'paused', 'onTogglePause']}>
 {({ currentTime, paused, onTogglePause }) => (
          <div>
              The track is {paused ? 'paused' : 'playing'}. The time is {currentTime}.
           </div>
)}
</PlayerContextConsumer>
```

Frustratingly, this creates:

`TypeError: Cannot read property 'hasOwnProperty' of null`

While I really appreciate your incredible work on this, I must admit that I find the documentation rather frustrating, as there doesn't seem to be a "hello world" illustration of how to use a `PlayerContextProvider` / `PlayerContextConsumer`.

Best,
rex

**Comment by benwiley4000** [comment]
And I'll wait to close are this issue until we add good getting started docs

**Comment by benwiley4000** [comment]
I'll also make a note for a better error message when you forget to put the consumer inside of a provider.

**Comment by benwiley4000** [comment]
And (sorry for all the comments), one other thing I noticed.. since you're using PlayerContextProvider, you ought to be using MediaPlayerControls (which will inherit the ancestor playerContext) instead of MediaPlayer (which will create its own internal playerContext that isn't shared with the rest of the app).

**Comment by rexmortus** [comment]
@benwiley4000 thanks so much for _all_ the comments! 😉 I appreciate you taking the time, and am glad the import of my issue was clear, the docs could definitely be improved but... you know what? I only just bothered to notice that you've only just recently cleared `2.0`, I'm sure you have plenty of other work to do (never mind your day job). Congratulations on the milestone, and thanks again for all your work 🎉 !

As I'm in Melbourne, Australia, I just now woke up. It's Sunday morning and thus the perfect time to run through your comments above. I'll report back! Cheers

**Comment by rexmortus** [comment]
I've tried to follow along, but I'm afraid there is still some lingering uncertainty. So let me break it down into the specific questions.

Firstly, when creating a `<MediaPlayerControls/>` element and the exposing its state via. a  `<PlayerContextProvider>, it should look like this (?): 

```
<PlayerContextProvider>
  <MediaPlayerControls />
</PlayerContextProvider>
```

Unfortunately, this creates the error: `TypeError: cannot read property '0' of undefined`. It's clear from reading the error message this is in connection with the `playlist` prop being undefined. I went ahead and added:

```
<PlaylistContextProvider playlist={[]}>...
```

Which solves the issue, however it is unclear from the documentation that you must provide a playlist to the `PlaylistContextProvider`. I see it appears in the list of `props`, but this is one particular area where improving the error messaging and/or the documentation could be very helpful.

Now, this works:

```
        <PlayerContextProvider
          autoplay={true}
          playlist={startingPlaylist}
        >
          <MediaPlayerControls
            controls={[ 'spacer', 'playpause', 'mute', 'spacer', 'progress' ]}
          />
        </PlayerContextProvider>
```

My understanding is that this should now expose the media player's API through a `PlayerContextConsumer` element, so let's move to that.

In your comments above, you wrote:

```
// good
<PlayerContextProvider>
  <div>
    <PlayerContextConsumer />
  </div>
</PlayerContextProvider>
```

I would assume that means I could do something along the lines of what's contained in the docs, here:

https://benwiley4000.github.io/cassette/styleguide/#playercontextconsumer-1

Specifically this example:

```
import { PlayerContextConsumer } from '@cassette/core';

<PlayerContextConsumer filterList={['currentTime', 'paused', 'onTogglePause']}>
  {({ currentTime, paused, onTogglePause }) => (
    <React.Fragment>
      <div>
        The track is {paused ? 'paused' : 'playing'}. The time is {currentTime}.
      </div>
      <button onClick={onTogglePause}>Toggle pause!</button>
    </React.Fragment>
  )}
</PlayerContextConsumer>;
```

Interestingly, this example is _unlike_ the one you wrote above, as the `PlayerContextConsumer` is not wrapped in a `PlayerContextProvider`. In fact, this example creates an error: `TypeError: Cannot read property 'hasOwnProperty' of null` which doesn't tell me much about what's going wrong.

Notably, when I wrap the `...Consumer` in a `...Provider` e.g.

```
              <PlayerContextProvider>
                <PlayerContextConsumer filterList={['onTogglePause']}>
                  {({onTogglePause }) => (
                    <Button basic onClick={onTogglePause}>
                      <Icon name="play"/> in Browser
                    </Button>
                  )}
                </PlayerContextConsumer>
              </PlayerContextProvider>
```

It creates the same error message as earlier: `TypeError: Cannot read property '0' of undefined`, which indicates that somehow the `props` I have priorly defined in the `...Provider` that wraps `...mediaControls` are not available here.

Sure enough, if I define a `playlist` `prop` on the `...provider` that wraps the `...consumer`, e.g.

```
              <PlayerContextProvider playlist={[]}>
                <PlayerContextConsumer filterList={['onTogglePause']}>
                  {({onTogglePause }) => (
                    <Button basic onClick={onTogglePause}>
                      <Icon name="play"/> in Browser
                    </Button>
                  )}
                </PlayerContextConsumer>
              </PlayerContextProvider>
```

 ...everything renders. However, this does not make sense to me. It appears as though I am not re-using the `...provider` I created earlier, and what's more (and more important), it's clear that the `...consumer` is not interacting with `...provider` that wraps the `...controls`, which is to say: this renders but does not pause the player!

Hopefully my issue makes sense. Again, I think my issue simply indicates that a `hello world` example would be extraordinarily useful. Once you've helped me understand how everything holds together, I would be more than happy to assist in the writing of the documentation!

Thanks again @benwiley4000 you're as we say in 🇦🇺  a bloody legend

**Comment by rexmortus** [comment]
There is one example in the docs which says:

```
<PlayerContextProvider {...providerProps}>
```

But it's not clear where said providerProps are coming from? Basically, I think where I'm at now is, it's not clear how to re-use the `...provider` that wraps the `...mediaControls` in other places in my application.

**Comment by rexmortus** [comment]
Ok, I see what I was doing wrong. Both the `...mediaControls` and the `...consumer` must be peer child elements of the same `...provider`.

This is _unlike_ the standard pattern for react context providers, I believe? 

In any case, I've got the bastard working now, and boy does it feel good!

**Comment by rexmortus** [comment]
Hey, let me just say again: THANK YOU! `@cassette` is a great piece of software and I'm very appreciative that you've done this work. When I've got the player all rigged up, I'll send you a link to my site (where I host podcasts, writing, and comics). All the best

**Comment by benwiley4000** [comment]
Hey! I will try to respond to this in a couple of hours. I'm definitely
starting to see things that are unclear about the documentation.. please
give me any more comments you have on ambiguity!

Ben

Le sam. 13 avr. 2019 18 h 59, Alec Sloman <notifications@github.com> a
écrit :

**Comment by rexmortus** [comment]
@benwiley4000 no rush, as I've got it working now! I would be happy to start a conversation about the documentation with you (one of my strong suits). Do you have an active chat for this project? Or just GH issues?

**Comment by benwiley4000** [comment]
@rexmortus all we have currently is GitHub issues. If you'd like to use something like Spectrum that would be fine! I haven't set it up though.

**Comment by benwiley4000** [comment]
@rexmortus Ok so a few notes:

1. In the documentation it *does* say that the `playlist` prop is required. If this wasn't clear enough, we can think about changing the way the "required" thing is displayed in the docs table.

![Screenshot from 2019-04-14 13-05-44](https://user-images.githubusercontent.com/13558253/56096440-2c315480-5eb6-11e9-9065-12cea4b6fd9e.png)

2. Yes, everything needs to be a descendant of the same `PlayerContextProvider` (unless you have multiple players on the same page, where you might be wrapping everything in a `PlayerContextGroup`). Sorry if that wasn't clear... and I can see how you might see the `PlayerContextConsumer` example and be led to believe you can just render that with no `PlayerContextProvider` ancestor. Do you have any suggestions for improving the docs? In the docs, it's actually inheriting a `PlayerContextProvider` that is rendered around the whole docs page, so maybe we need to draw attention to that in the docs themselves. We should also update the error message to be less cryptic.

3. As far as `{...providerProps}` -- that was just meant to signify whatever props you choose to pass. Maybe that could use some additional clarity as well.

What are your thoughts on the best way to proceed with documentation discussions? GitHub Issues? Spectrum? Gitter?

And thanks again for the detailed brain dump while you figured this out! It's helpful for me seeing how the docs are perceived/could be improved.

**Comment by benwiley4000** [comment]
> Ok, I see what I was doing wrong. Both the ...mediaControls and the ...consumer must be peer child elements of the same ...provider.
>
> This is unlike the standard pattern for react context providers, I believe?

Here's what I think you might have missed - `MediaPlayerControls` renders its own `PlayerContextConsumer` and for other stuff you need to render it yourself.

This can definitely make stuff seem confusing, I guess. Do you think there's a way we could make that more clear?

**Comment by benwiley4000** [comment]
@rexmortus hey, just wanted to follow up - any thoughts on what I wrote above? 🙂

**Comment by benwiley4000** [comment]
Hey @rexmortus how's this for a quickstart doc?

https://github.com/benwiley4000/cassette/blob/next/quickstart.md

(The images are broken in the actual docs page at the moment; trying to figure out how I can have a markdown file with images that works in both the repo and in the compiled/deployed styleguide.)

**Comment by benwiley4000** [comment]
I actually ended up figuring this one out. https://benwiley4000.github.io/cassette/styleguide

**Comment by rexmortus** [comment]
@benwiley4000  👍for the quickstart documentation, you absolutely nailed it which suggests to me that you clearly understood why it was needed. 💯 

FYI, I have made great use of `cassette` on my personal website, including use of the `ContextProvider` to interact with a persistent player from within page elements.

*desktop only*

https://www.rexmort.us/senecast

☝️ Have a look! 

Again, thank you so much for your work on this. I really appreciate it.

**Comment by benwiley4000** [comment]
@rexmortus wow that looks awesome (and works great on mobile if you turn on desktop spoofing!). Mind if I stick a link in the readme as an example of Cassette in the wild?

**Comment by rexmortus** [comment]
Sure thing, Ben! Thanks again for your work - it has helped me realise my own work in a very real way.

**Comment by benwiley4000** [comment]
Great, thanks! I'll close this issue since it seems the onramp problem is resolved.

**Comment by rexmortus** [comment]
Yep, sounds good to me
